// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.29.4
// source: proto/mcp-service/skill-service.proto

package mcp_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- custom skill ---
type CustomSkill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkillId    string `protobuf:"bytes,1,opt,name=skillId,proto3" json:"skillId,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar     string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Author     string `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Desc       string `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	ObjectPath string `protobuf:"bytes,6,opt,name=objectPath,proto3" json:"objectPath,omitempty"`
	Markdown   string `protobuf:"bytes,9,opt,name=markdown,proto3" json:"markdown,omitempty"`
	CreatedAt  int64  `protobuf:"varint,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt  int64  `protobuf:"varint,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *CustomSkill) Reset() {
	*x = CustomSkill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mcp_service_skill_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomSkill) ProtoMessage() {}

func (x *CustomSkill) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_service_skill_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomSkill.ProtoReflect.Descriptor instead.
func (*CustomSkill) Descriptor() ([]byte, []int) {
	return file_proto_mcp_service_skill_service_proto_rawDescGZIP(), []int{0}
}

func (x *CustomSkill) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *CustomSkill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomSkill) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CustomSkill) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CustomSkill) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CustomSkill) GetObjectPath() string {
	if x != nil {
		return x.ObjectPath
	}
	return ""
}

func (x *CustomSkill) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

func (x *CustomSkill) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CustomSkill) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CustomSkillCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Avatar     string    `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Author     string    `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Desc       string    `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	ObjectPath string    `protobuf:"bytes,5,opt,name=objectPath,proto3" json:"objectPath,omitempty"`
	SaveId     string    `protobuf:"bytes,6,opt,name=saveId,proto3" json:"saveId,omitempty"`
	SourceType string    `protobuf:"bytes,7,opt,name=sourceType,proto3" json:"sourceType,omitempty"`
	Identity   *Identity `protobuf:"bytes,8,opt,name=identity,proto3" json:"identity,omitempty"`
	Markdown   string    `protobuf:"bytes,9,opt,name=markdown,proto3" json:"markdown,omitempty"`
}

func (x *CustomSkillCreateReq) Reset() {
	*x = CustomSkillCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mcp_service_skill_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomSkillCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomSkillCreateReq) ProtoMessage() {}

func (x *CustomSkillCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_service_skill_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomSkillCreateReq.ProtoReflect.Descriptor instead.
func (*CustomSkillCreateReq) Descriptor() ([]byte, []int) {
	return file_proto_mcp_service_skill_service_proto_rawDescGZIP(), []int{1}
}

func (x *CustomSkillCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomSkillCreateReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CustomSkillCreateReq) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CustomSkillCreateReq) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CustomSkillCreateReq) GetObjectPath() string {
	if x != nil {
		return x.ObjectPath
	}
	return ""
}

func (x *CustomSkillCreateReq) GetSaveId() string {
	if x != nil {
		return x.SaveId
	}
	return ""
}

func (x *CustomSkillCreateReq) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *CustomSkillCreateReq) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *CustomSkillCreateReq) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

type CustomSkillCreateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkillId string `protobuf:"bytes,1,opt,name=skillId,proto3" json:"skillId,omitempty"`
}

func (x *CustomSkillCreateResp) Reset() {
	*x = CustomSkillCreateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mcp_service_skill_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomSkillCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomSkillCreateResp) ProtoMessage() {}

func (x *CustomSkillCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_service_skill_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomSkillCreateResp.ProtoReflect.Descriptor instead.
func (*CustomSkillCreateResp) Descriptor() ([]byte, []int) {
	return file_proto_mcp_service_skill_service_proto_rawDescGZIP(), []int{2}
}

func (x *CustomSkillCreateResp) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

type CustomSkillDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkillId string `protobuf:"bytes,1,opt,name=skillId,proto3" json:"skillId,omitempty"`
}

func (x *CustomSkillDeleteReq) Reset() {
	*x = CustomSkillDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mcp_service_skill_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomSkillDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomSkillDeleteReq) ProtoMessage() {}

func (x *CustomSkillDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_service_skill_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomSkillDeleteReq.ProtoReflect.Descriptor instead.
func (*CustomSkillDeleteReq) Descriptor() ([]byte, []int) {
	return file_proto_mcp_service_skill_service_proto_rawDescGZIP(), []int{3}
}

func (x *CustomSkillDeleteReq) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

type CustomSkillGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkillId  string    `protobuf:"bytes,1,opt,name=skillId,proto3" json:"skillId,omitempty"`
	Identity *Identity `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
}

func (x *CustomSkillGetReq) Reset() {
	*x = CustomSkillGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mcp_service_skill_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomSkillGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomSkillGetReq) ProtoMessage() {}

func (x *CustomSkillGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_service_skill_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomSkillGetReq.ProtoReflect.Descriptor instead.
func (*CustomSkillGetReq) Descriptor() ([]byte, []int) {
	return file_proto_mcp_service_skill_service_proto_rawDescGZIP(), []int{4}
}

func (x *CustomSkillGetReq) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *CustomSkillGetReq) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type CustomSkillGetListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Page     int32     `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32     `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Identity *Identity `protobuf:"bytes,4,opt,name=identity,proto3" json:"identity,omitempty"`
}

func (x *CustomSkillGetListReq) Reset() {
	*x = CustomSkillGetListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mcp_service_skill_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomSkillGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomSkillGetListReq) ProtoMessage() {}

func (x *CustomSkillGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_service_skill_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomSkillGetListReq.ProtoReflect.Descriptor instead.
func (*CustomSkillGetListReq) Descriptor() ([]byte, []int) {
	return file_proto_mcp_service_skill_service_proto_rawDescGZIP(), []int{5}
}

func (x *CustomSkillGetListReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomSkillGetListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CustomSkillGetListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *CustomSkillGetListReq) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type CustomSkillGetListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*CustomSkill `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total int64          `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *CustomSkillGetListResp) Reset() {
	*x = CustomSkillGetListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mcp_service_skill_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomSkillGetListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomSkillGetListResp) ProtoMessage() {}

func (x *CustomSkillGetListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_service_skill_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomSkillGetListResp.ProtoReflect.Descriptor instead.
func (*CustomSkillGetListResp) Descriptor() ([]byte, []int) {
	return file_proto_mcp_service_skill_service_proto_rawDescGZIP(), []int{6}
}

func (x *CustomSkillGetListResp) GetList() []*CustomSkill {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *CustomSkillGetListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CustomSkillGetBySaveIdsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SaveIds []string `protobuf:"bytes,1,rep,name=saveIds,proto3" json:"saveIds,omitempty"`
}

func (x *CustomSkillGetBySaveIdsReq) Reset() {
	*x = CustomSkillGetBySaveIdsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mcp_service_skill_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomSkillGetBySaveIdsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomSkillGetBySaveIdsReq) ProtoMessage() {}

func (x *CustomSkillGetBySaveIdsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_service_skill_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomSkillGetBySaveIdsReq.ProtoReflect.Descriptor instead.
func (*CustomSkillGetBySaveIdsReq) Descriptor() ([]byte, []int) {
	return file_proto_mcp_service_skill_service_proto_rawDescGZIP(), []int{7}
}

func (x *CustomSkillGetBySaveIdsReq) GetSaveIds() []string {
	if x != nil {
		return x.SaveIds
	}
	return nil
}

type CustomSkillSaveIdsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SaveIds []string `protobuf:"bytes,1,rep,name=saveIds,proto3" json:"saveIds,omitempty"`
}

func (x *CustomSkillSaveIdsResp) Reset() {
	*x = CustomSkillSaveIdsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mcp_service_skill_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomSkillSaveIdsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomSkillSaveIdsResp) ProtoMessage() {}

func (x *CustomSkillSaveIdsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_service_skill_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomSkillSaveIdsResp.ProtoReflect.Descriptor instead.
func (*CustomSkillSaveIdsResp) Descriptor() ([]byte, []int) {
	return file_proto_mcp_service_skill_service_proto_rawDescGZIP(), []int{8}
}

func (x *CustomSkillSaveIdsResp) GetSaveIds() []string {
	if x != nil {
		return x.SaveIds
	}
	return nil
}

type CustomSkillDetailByIdListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkillIds []string `protobuf:"bytes,1,rep,name=skillIds,proto3" json:"skillIds,omitempty"`
}

func (x *CustomSkillDetailByIdListReq) Reset() {
	*x = CustomSkillDetailByIdListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mcp_service_skill_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomSkillDetailByIdListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomSkillDetailByIdListReq) ProtoMessage() {}

func (x *CustomSkillDetailByIdListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_service_skill_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomSkillDetailByIdListReq.ProtoReflect.Descriptor instead.
func (*CustomSkillDetailByIdListReq) Descriptor() ([]byte, []int) {
	return file_proto_mcp_service_skill_service_proto_rawDescGZIP(), []int{9}
}

func (x *CustomSkillDetailByIdListReq) GetSkillIds() []string {
	if x != nil {
		return x.SkillIds
	}
	return nil
}

type CustomSkillDetailByIdListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkillDetails []*CustomSkill `protobuf:"bytes,1,rep,name=skillDetails,proto3" json:"skillDetails,omitempty"`
}

func (x *CustomSkillDetailByIdListResp) Reset() {
	*x = CustomSkillDetailByIdListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mcp_service_skill_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomSkillDetailByIdListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomSkillDetailByIdListResp) ProtoMessage() {}

func (x *CustomSkillDetailByIdListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_service_skill_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomSkillDetailByIdListResp.ProtoReflect.Descriptor instead.
func (*CustomSkillDetailByIdListResp) Descriptor() ([]byte, []int) {
	return file_proto_mcp_service_skill_service_proto_rawDescGZIP(), []int{10}
}

func (x *CustomSkillDetailByIdListResp) GetSkillDetails() []*CustomSkill {
	if x != nil {
		return x.SkillDetails
	}
	return nil
}

// --- acquired skill ---
type AcquiredSkill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AcquiredSkillId    string `protobuf:"bytes,1,opt,name=acquiredSkillId,proto3" json:"acquiredSkillId,omitempty"`
	SquareSkillId      string `protobuf:"bytes,2,opt,name=squareSkillId,proto3" json:"squareSkillId,omitempty"`
	Name               string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Avatar             string `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Author             string `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	AuthorId           string `protobuf:"bytes,6,opt,name=authorId,proto3" json:"authorId,omitempty"`
	Desc               string `protobuf:"bytes,7,opt,name=desc,proto3" json:"desc,omitempty"`
	ObjectPath         string `protobuf:"bytes,8,opt,name=objectPath,proto3" json:"objectPath,omitempty"`
	Markdown           string `protobuf:"bytes,9,opt,name=markdown,proto3" json:"markdown,omitempty"`
	AcquiredType       string `protobuf:"bytes,10,opt,name=acquiredType,proto3" json:"acquiredType,omitempty"` //builtin/custom
	Version            string `protobuf:"bytes,11,opt,name=version,proto3" json:"version,omitempty"`
	VersionDescription string `protobuf:"bytes,12,opt,name=versionDescription,proto3" json:"versionDescription,omitempty"`
	CreatedAt          int64  `protobuf:"varint,13,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt          int64  `protobuf:"varint,14,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *AcquiredSkill) Reset() {
	*x = AcquiredSkill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mcp_service_skill_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcquiredSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquiredSkill) ProtoMessage() {}

func (x *AcquiredSkill) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_service_skill_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquiredSkill.ProtoReflect.Descriptor instead.
func (*AcquiredSkill) Descriptor() ([]byte, []int) {
	return file_proto_mcp_service_skill_service_proto_rawDescGZIP(), []int{11}
}

func (x *AcquiredSkill) GetAcquiredSkillId() string {
	if x != nil {
		return x.AcquiredSkillId
	}
	return ""
}

func (x *AcquiredSkill) GetSquareSkillId() string {
	if x != nil {
		return x.SquareSkillId
	}
	return ""
}

func (x *AcquiredSkill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AcquiredSkill) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *AcquiredSkill) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *AcquiredSkill) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *AcquiredSkill) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *AcquiredSkill) GetObjectPath() string {
	if x != nil {
		return x.ObjectPath
	}
	return ""
}

func (x *AcquiredSkill) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

func (x *AcquiredSkill) GetAcquiredType() string {
	if x != nil {
		return x.AcquiredType
	}
	return ""
}

func (x *AcquiredSkill) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AcquiredSkill) GetVersionDescription() string {
	if x != nil {
		return x.VersionDescription
	}
	return ""
}

func (x *AcquiredSkill) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AcquiredSkill) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type AcquiredSkillCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity           *Identity `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Name               string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar             string    `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	SquareSkillId      string    `protobuf:"bytes,4,opt,name=squareSkillId,proto3" json:"squareSkillId,omitempty"`
	Author             string    `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	AuthorId           string    `protobuf:"bytes,6,opt,name=authorId,proto3" json:"authorId,omitempty"`
	Desc               string    `protobuf:"bytes,7,opt,name=desc,proto3" json:"desc,omitempty"`
	ObjectPath         string    `protobuf:"bytes,8,opt,name=objectPath,proto3" json:"objectPath,omitempty"`
	AcquiredType       string    `protobuf:"bytes,9,opt,name=acquiredType,proto3" json:"acquiredType,omitempty"` //builtin/custom
	Markdown           string    `protobuf:"bytes,10,opt,name=markdown,proto3" json:"markdown,omitempty"`
	Version            string    `protobuf:"bytes,11,opt,name=version,proto3" json:"version,omitempty"`
	VersionDescription string    `protobuf:"bytes,12,opt,name=versionDescription,proto3" json:"versionDescription,omitempty"`
}

func (x *AcquiredSkillCreateReq) Reset() {
	*x = AcquiredSkillCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mcp_service_skill_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcquiredSkillCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquiredSkillCreateReq) ProtoMessage() {}

func (x *AcquiredSkillCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_service_skill_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquiredSkillCreateReq.ProtoReflect.Descriptor instead.
func (*AcquiredSkillCreateReq) Descriptor() ([]byte, []int) {
	return file_proto_mcp_service_skill_service_proto_rawDescGZIP(), []int{12}
}

func (x *AcquiredSkillCreateReq) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *AcquiredSkillCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AcquiredSkillCreateReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *AcquiredSkillCreateReq) GetSquareSkillId() string {
	if x != nil {
		return x.SquareSkillId
	}
	return ""
}

func (x *AcquiredSkillCreateReq) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *AcquiredSkillCreateReq) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *AcquiredSkillCreateReq) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *AcquiredSkillCreateReq) GetObjectPath() string {
	if x != nil {
		return x.ObjectPath
	}
	return ""
}

func (x *AcquiredSkillCreateReq) GetAcquiredType() string {
	if x != nil {
		return x.AcquiredType
	}
	return ""
}

func (x *AcquiredSkillCreateReq) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

func (x *AcquiredSkillCreateReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AcquiredSkillCreateReq) GetVersionDescription() string {
	if x != nil {
		return x.VersionDescription
	}
	return ""
}

type AcquiredSkillCreateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AcquiredSkillId string `protobuf:"bytes,1,opt,name=acquiredSkillId,proto3" json:"acquiredSkillId,omitempty"`
}

func (x *AcquiredSkillCreateResp) Reset() {
	*x = AcquiredSkillCreateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mcp_service_skill_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcquiredSkillCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquiredSkillCreateResp) ProtoMessage() {}

func (x *AcquiredSkillCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_service_skill_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquiredSkillCreateResp.ProtoReflect.Descriptor instead.
func (*AcquiredSkillCreateResp) Descriptor() ([]byte, []int) {
	return file_proto_mcp_service_skill_service_proto_rawDescGZIP(), []int{13}
}

func (x *AcquiredSkillCreateResp) GetAcquiredSkillId() string {
	if x != nil {
		return x.AcquiredSkillId
	}
	return ""
}

type AcquiredSkillDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AcquiredSkillId string `protobuf:"bytes,1,opt,name=acquiredSkillId,proto3" json:"acquiredSkillId,omitempty"`
}

func (x *AcquiredSkillDeleteReq) Reset() {
	*x = AcquiredSkillDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mcp_service_skill_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcquiredSkillDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquiredSkillDeleteReq) ProtoMessage() {}

func (x *AcquiredSkillDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_service_skill_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquiredSkillDeleteReq.ProtoReflect.Descriptor instead.
func (*AcquiredSkillDeleteReq) Descriptor() ([]byte, []int) {
	return file_proto_mcp_service_skill_service_proto_rawDescGZIP(), []int{14}
}

func (x *AcquiredSkillDeleteReq) GetAcquiredSkillId() string {
	if x != nil {
		return x.AcquiredSkillId
	}
	return ""
}

type AcquiredSkillGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AcquiredSkillId string `protobuf:"bytes,1,opt,name=acquiredSkillId,proto3" json:"acquiredSkillId,omitempty"`
}

func (x *AcquiredSkillGetReq) Reset() {
	*x = AcquiredSkillGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mcp_service_skill_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcquiredSkillGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquiredSkillGetReq) ProtoMessage() {}

func (x *AcquiredSkillGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_service_skill_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquiredSkillGetReq.ProtoReflect.Descriptor instead.
func (*AcquiredSkillGetReq) Descriptor() ([]byte, []int) {
	return file_proto_mcp_service_skill_service_proto_rawDescGZIP(), []int{15}
}

func (x *AcquiredSkillGetReq) GetAcquiredSkillId() string {
	if x != nil {
		return x.AcquiredSkillId
	}
	return ""
}

type AcquiredSkillGetListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity *Identity `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Name     string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *AcquiredSkillGetListReq) Reset() {
	*x = AcquiredSkillGetListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mcp_service_skill_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcquiredSkillGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquiredSkillGetListReq) ProtoMessage() {}

func (x *AcquiredSkillGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_service_skill_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquiredSkillGetListReq.ProtoReflect.Descriptor instead.
func (*AcquiredSkillGetListReq) Descriptor() ([]byte, []int) {
	return file_proto_mcp_service_skill_service_proto_rawDescGZIP(), []int{16}
}

func (x *AcquiredSkillGetListReq) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *AcquiredSkillGetListReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AcquiredSkillGetListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*AcquiredSkill `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total int64            `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *AcquiredSkillGetListResp) Reset() {
	*x = AcquiredSkillGetListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mcp_service_skill_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcquiredSkillGetListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquiredSkillGetListResp) ProtoMessage() {}

func (x *AcquiredSkillGetListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mcp_service_skill_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquiredSkillGetListResp.ProtoReflect.Descriptor instead.
func (*AcquiredSkillGetListResp) Descriptor() ([]byte, []int) {
	return file_proto_mcp_service_skill_service_proto_rawDescGZIP(), []int{17}
}

func (x *AcquiredSkillGetListResp) GetList() []*AcquiredSkill {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *AcquiredSkillGetListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_mcp_service_skill_service_proto protoreflect.FileDescriptor

var file_proto_mcp_service_skill_service_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x63, 0x70, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x63, 0x70, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x1a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x63, 0x70, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf7, 0x01, 0x0a, 0x0b, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x53,
	0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x50, 0x61, 0x74, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x72, 0x6b, 0x64, 0x6f,
	0x77, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x61, 0x72, 0x6b, 0x64, 0x6f,
	0x77, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x95,
	0x02, 0x0a, 0x14, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x65, 0x73, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12,
	0x1e, 0x0a, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x61, 0x74, 0x68, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x61, 0x76, 0x65, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x61, 0x76, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x63, 0x70, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61,
	0x72, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x61,
	0x72, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x22, 0x31, 0x0a, 0x15, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x22, 0x30, 0x0a, 0x14, 0x43, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x22, 0x60, 0x0a, 0x11, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x31, 0x0a, 0x08, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d,
	0x63, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x8e, 0x01,
	0x0a, 0x15, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x65, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x6d, 0x63, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x5c,
	0x0a, 0x16, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x65, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x63, 0x70, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x53, 0x6b, 0x69, 0x6c, 0x6c,
	0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x36, 0x0a, 0x1a,
	0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x65, 0x74, 0x42, 0x79,
	0x53, 0x61, 0x76, 0x65, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x61,
	0x76, 0x65, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x61, 0x76,
	0x65, 0x49, 0x64, 0x73, 0x22, 0x32, 0x0a, 0x16, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x53, 0x6b,
	0x69, 0x6c, 0x6c, 0x53, 0x61, 0x76, 0x65, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x61, 0x76, 0x65, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x61, 0x76, 0x65, 0x49, 0x64, 0x73, 0x22, 0x3a, 0x0a, 0x1c, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x42, 0x79, 0x49,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6b, 0x69, 0x6c,
	0x6c, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6b, 0x69, 0x6c,
	0x6c, 0x49, 0x64, 0x73, 0x22, 0x5d, 0x0a, 0x1d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x53, 0x6b,
	0x69, 0x6c, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x42, 0x79, 0x49, 0x64, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3c, 0x0a, 0x0c, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x63,
	0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x0c, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x22, 0xb9, 0x03, 0x0a, 0x0d, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64,
	0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x28, 0x0a, 0x0f, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x64, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x12,
	0x24, 0x0a, 0x0d, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x53, 0x6b,
	0x69, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x50, 0x61, 0x74, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x72,
	0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x61, 0x72,
	0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x63, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x12, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x12, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0e,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22,
	0x8f, 0x03, 0x0a, 0x16, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x53, 0x6b, 0x69, 0x6c,
	0x6c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x31, 0x0a, 0x08, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d,
	0x63, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x71, 0x75,
	0x61, 0x72, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x50, 0x61, 0x74, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x63, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61,
	0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d,
	0x61, 0x72, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d,
	0x61, 0x72, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x2e, 0x0a, 0x12, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x43, 0x0a, 0x17, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x53, 0x6b, 0x69,
	0x6c, 0x6c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x0f,
	0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x53,
	0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x22, 0x42, 0x0a, 0x16, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x64, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x28, 0x0a, 0x0f, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x53, 0x6b, 0x69, 0x6c,
	0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x63, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x64, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x22, 0x3f, 0x0a, 0x13, 0x41, 0x63,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x28, 0x0a, 0x0f, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x53, 0x6b, 0x69,
	0x6c, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x63, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x64, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x22, 0x60, 0x0a, 0x17, 0x41,
	0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x31, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x63, 0x70, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52,
	0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x60, 0x0a,
	0x18, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x63, 0x70, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x53, 0x6b,
	0x69, 0x6c, 0x6c, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x42,
	0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x55, 0x6e,
	0x69, 0x63, 0x6f, 0x6d, 0x41, 0x49, 0x2f, 0x77, 0x61, 0x6e, 0x77, 0x75, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x63, 0x70, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_mcp_service_skill_service_proto_rawDescOnce sync.Once
	file_proto_mcp_service_skill_service_proto_rawDescData = file_proto_mcp_service_skill_service_proto_rawDesc
)

func file_proto_mcp_service_skill_service_proto_rawDescGZIP() []byte {
	file_proto_mcp_service_skill_service_proto_rawDescOnce.Do(func() {
		file_proto_mcp_service_skill_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_mcp_service_skill_service_proto_rawDescData)
	})
	return file_proto_mcp_service_skill_service_proto_rawDescData
}

var file_proto_mcp_service_skill_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_mcp_service_skill_service_proto_goTypes = []interface{}{
	(*CustomSkill)(nil),                   // 0: mcp_service.CustomSkill
	(*CustomSkillCreateReq)(nil),          // 1: mcp_service.CustomSkillCreateReq
	(*CustomSkillCreateResp)(nil),         // 2: mcp_service.CustomSkillCreateResp
	(*CustomSkillDeleteReq)(nil),          // 3: mcp_service.CustomSkillDeleteReq
	(*CustomSkillGetReq)(nil),             // 4: mcp_service.CustomSkillGetReq
	(*CustomSkillGetListReq)(nil),         // 5: mcp_service.CustomSkillGetListReq
	(*CustomSkillGetListResp)(nil),        // 6: mcp_service.CustomSkillGetListResp
	(*CustomSkillGetBySaveIdsReq)(nil),    // 7: mcp_service.CustomSkillGetBySaveIdsReq
	(*CustomSkillSaveIdsResp)(nil),        // 8: mcp_service.CustomSkillSaveIdsResp
	(*CustomSkillDetailByIdListReq)(nil),  // 9: mcp_service.CustomSkillDetailByIdListReq
	(*CustomSkillDetailByIdListResp)(nil), // 10: mcp_service.CustomSkillDetailByIdListResp
	(*AcquiredSkill)(nil),                 // 11: mcp_service.AcquiredSkill
	(*AcquiredSkillCreateReq)(nil),        // 12: mcp_service.AcquiredSkillCreateReq
	(*AcquiredSkillCreateResp)(nil),       // 13: mcp_service.AcquiredSkillCreateResp
	(*AcquiredSkillDeleteReq)(nil),        // 14: mcp_service.AcquiredSkillDeleteReq
	(*AcquiredSkillGetReq)(nil),           // 15: mcp_service.AcquiredSkillGetReq
	(*AcquiredSkillGetListReq)(nil),       // 16: mcp_service.AcquiredSkillGetListReq
	(*AcquiredSkillGetListResp)(nil),      // 17: mcp_service.AcquiredSkillGetListResp
	(*Identity)(nil),                      // 18: mcp_service.Identity
}
var file_proto_mcp_service_skill_service_proto_depIdxs = []int32{
	18, // 0: mcp_service.CustomSkillCreateReq.identity:type_name -> mcp_service.Identity
	18, // 1: mcp_service.CustomSkillGetReq.identity:type_name -> mcp_service.Identity
	18, // 2: mcp_service.CustomSkillGetListReq.identity:type_name -> mcp_service.Identity
	0,  // 3: mcp_service.CustomSkillGetListResp.list:type_name -> mcp_service.CustomSkill
	0,  // 4: mcp_service.CustomSkillDetailByIdListResp.skillDetails:type_name -> mcp_service.CustomSkill
	18, // 5: mcp_service.AcquiredSkillCreateReq.identity:type_name -> mcp_service.Identity
	18, // 6: mcp_service.AcquiredSkillGetListReq.identity:type_name -> mcp_service.Identity
	11, // 7: mcp_service.AcquiredSkillGetListResp.list:type_name -> mcp_service.AcquiredSkill
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_mcp_service_skill_service_proto_init() }
func file_proto_mcp_service_skill_service_proto_init() {
	if File_proto_mcp_service_skill_service_proto != nil {
		return
	}
	file_proto_mcp_service_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_mcp_service_skill_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomSkill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mcp_service_skill_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomSkillCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mcp_service_skill_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomSkillCreateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mcp_service_skill_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomSkillDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mcp_service_skill_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomSkillGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mcp_service_skill_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomSkillGetListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mcp_service_skill_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomSkillGetListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mcp_service_skill_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomSkillGetBySaveIdsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mcp_service_skill_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomSkillSaveIdsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mcp_service_skill_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomSkillDetailByIdListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mcp_service_skill_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomSkillDetailByIdListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mcp_service_skill_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcquiredSkill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mcp_service_skill_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcquiredSkillCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mcp_service_skill_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcquiredSkillCreateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mcp_service_skill_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcquiredSkillDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mcp_service_skill_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcquiredSkillGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mcp_service_skill_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcquiredSkillGetListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mcp_service_skill_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcquiredSkillGetListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_mcp_service_skill_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_mcp_service_skill_service_proto_goTypes,
		DependencyIndexes: file_proto_mcp_service_skill_service_proto_depIdxs,
		MessageInfos:      file_proto_mcp_service_skill_service_proto_msgTypes,
	}.Build()
	File_proto_mcp_service_skill_service_proto = out.File
	file_proto_mcp_service_skill_service_proto_rawDesc = nil
	file_proto_mcp_service_skill_service_proto_goTypes = nil
	file_proto_mcp_service_skill_service_proto_depIdxs = nil
}
